### ISSUE TITLE
Not run 

### ISSUE THREAD

**Issue by mrthanduc** [nallath/PrintCostCalculator#1]
I can see it on Extensions Menu but it not show any extra windows @@

**Comment by nallath** [comment]
I'm going to need more information before I can help you. Please look at https://github.com/Ultimaker/Cura#logging-issues to see what kind of info I need.

**Comment by erikstiff** [comment]
I have the same problem! I can see the plug-in but there is no window after clicking on the extension menu.

**Comment by nallath** [comment]
I can't help you if your only information is 'It doesn't work'. Look at the logging-issues link I posted.
