### ISSUE TITLE
Does not Calculate

### ISSUE THREAD

**Issue by lilmac024** [nallath/PrintCostCalculator#2]
When I attempt to use it, I get the window that pops up, but no matter what I do, the window says weight 0, price 0.  How do I get this to reflect the model?

Thanks!

**Comment by nallath** [comment]
Does the model slice at all? If there is no sliced model, it won't have any data to work with.

**Comment by lilmac024** [comment]
This appears to be the issue...for some reason none of my models are showing in the layer mode.  Is this a known problem with the new release, or is there something simple I'm missing?

**Comment by nallath** [comment]
We did make some fixes for the layerview in the new (beta) version.

**Comment by lilmac024** [comment]
ok, hopefully this will be resolved with the next release then.  Until then, I'll just wait.  I assume that's also why my time estimate just says "calculating" as well.

**Comment by nallath** [comment]
Yeah, this sounds like an issue with Cura itself, not so much with the plugin.
