### ISSUE TITLE
Cura 3.x and 4.x Integration

### ISSUE THREAD

**Issue by mmgarcia30** [nallath/PrintCostCalculator#9]
Hi team

The plugin no longer works in current versions of Cura 3.x, 4.x, due the new plugin interface and the migration to Python 3.x

Please can you adapt them to this new and future releases.

Regards

**Comment by nallath** [comment]
Migration to python 3.x? This plugin has always been python 3.0

Due to the integration of the print cost into the main interface of Cura, i never updated this plugin. It was originally mostly intended to be an example plugin.
